<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst($report->type) }} Report</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; }
        h1 { color: #1f2937; border-bottom: 2px solid #3B82F6; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #3B82F6; color: white; padding: 10px; text-align: left; }
        td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f9fafb; }
        .meta { color: #6b7280; margin-bottom: 20px; }
    </style>
</head>
<body>
    <h1>{{ ucfirst($report->type) }} Report #{{ $report->id }}</h1>
    <div class="meta">
        <p><strong>Period:</strong> {{ $report->start_date->format('M d, Y') }} - {{ $report->end_date->format('M d, Y') }}</p>
        <p><strong>Generated:</strong> {{ $report->updated_at->format('M d, Y H:i') }}</p>
        <p><strong>Generated By:</strong> {{ $report->generator?->name ?? 'System' }}</p>
    </div>

    <table>
        <thead>
            <tr>
                @foreach($data[0] as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach(array_slice($data, 1) as $row)
                <tr>
                    @foreach($row as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>